version: 0.2

phases:
  install:
    commands:
        - echo 'which pip3'
        - /usr/local/bin/pip3 install Flask -i https://pypi.tuna.tsinghua.edu.cn/simple
        #/usr/local/bin/pip3 install flask
        #python -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
